name: Cloud Unzip

on:
  workflow_dispatch:

jobs:
  unzip_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Zip Archive
        run: |
          unzip -o *.zip
          rm *.zip

      - name: Save Changes to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Extracted bulk files via cloud action"
          git push
